USE `postventa_test`;

INSERT INTO `categorias` (`nombre_categoria`, `subcategoria`, `descripcion`) VALUES
('Carpintería', 'Puertas', 'Problemas con puertas, marcos y cerraduras'),
('Carpintería', 'Ventanas', 'Fallas en ventanas, correderas y sellos'),
('Carpintería', 'Closets', 'Problemas en closets y muebles empotrados'),
('Electricidad', 'Enchufes', 'Enchufes sueltos, quemados o sin corriente'),
('Electricidad', 'Iluminación', 'Problemas con luminarias y focos'),
('Instalaciones Sanitarias', 'WC', 'Problemas con inodoros y estanques'),
('Instalaciones Sanitarias', 'Desagües', 'Obstrucciones y malos olores'),
('Terminaciones', 'Muros', 'Grietas, fisuras y problemas estructurales'),
('Terminaciones', 'Pisos', 'Problemas en pisos flotantes o porcelanato'),
('Terminaciones', 'Cielos', 'Manchas de humedad o desprendimientos'),
('Vidrios', 'Ventanas', 'Vidrios quebrados o con filtraciones'),
('Vidrios', 'Mamparas', 'Problemas en mamparas de baño'),
('Aislación', 'Térmica', 'Problemas de aislación térmica'),
('Aislación', 'Acústica', 'Filtraciones de ruido entre departamentos');

INSERT INTO `clientes` (`nombre_empresa`, `rut`, `correo_contacto`, `telefono`, `direccion`, `estado`) VALUES
('Inmobiliaria Vista Hermosa', '77.234.567-8', 'contacto@vistahermosa.cl', '+56922223333', 'Av. Providencia 2500, Santiago', 'Activo'),
('Constructora Del Sur', '78.345.678-9', 'proyectos@delsur.cl', '+56933334444', 'Av. Libertador Bernardo O\'Higgins 1234', 'Activo'),
('Inversiones Pacifico S.A.', '79.456.789-0', 'admin@pacifico.cl', '+56944445555', 'Av. Apoquindo 4500, Las Condes', 'Activo'),
('Desarrollos Urbanos Ltda.', '80.567.890-1', 'info@desarrollosurbanos.cl', '+56955556666', 'Av. Vicuña Mackenna 7000, La Florida', 'Activo'),
('Inmobiliaria Costa Verde', '81.678.901-2', 'ventas@costaverde.cl', '+56966667777', 'Av. del Mar 1500, Viña del Mar', 'Activo');

INSERT INTO `obras` (`id_cliente`, `nombre_obra`, `descripcion_obra`, `direccion`, `planos_presupuestos`, `fecha_entrega`, `garantia_expira`, `estado_obra`) VALUES
(3, 'Condominio Las Palmas', 'Condominio de 30 casas', 'Camino Las Palmas 2000, Peñalolén', 'https://storage.pitagora.cl/planos/las_palmas.pdf', '2025-08-20', '2028-08-20', 'Activa'),
(4, 'Torre Mirador', 'Edificio de 20 pisos con vista al mar', 'Av. Borgoño 15000, Viña del Mar', 'https://storage.pitagora.cl/planos/torre_mirador.pdf', '2025-11-30', '2028-11-30', 'Activa'),
(5, 'Edificio Parque Central', 'Edificio residencial 12 pisos', 'Av. Grecia 8000, Ñuñoa', 'https://storage.pitagora.cl/planos/parque_central.pdf', '2025-09-15', '2028-09-15', 'Activa'),
(1, 'Edificio Los Robles', 'Edificio residencial 10 pisos', 'Calle Los Robles 890, Providencia', 'https://storage.pitagora.cl/planos/los_robles.pdf', '2025-07-10', '2028-07-10', 'Activa'),
(2, 'Bodega Industrial Norte', 'Complejo de bodegas 8000m2', 'Ruta 5 Norte km 25, Lampa', 'https://storage.pitagora.cl/planos/bodega_norte.pdf', '2026-03-15', '2029-03-15', 'Activa'),
(3, 'Edificio Vista Mar', 'Edificio frente al mar 8 pisos', 'Av. Marina 3000, Concón', 'https://storage.pitagora.cl/planos/vista_mar.pdf', '2024-12-20', '2027-12-20', 'Activa');

INSERT INTO `usuarios` (`nombre`, `correo`, `password`, `rol`, `id_obra`, `telefono`, `estado`) VALUES
('María González', 'mgonzalez@pitagora.cl', 'admin123', 'admin', NULL, '+56977778888', 'Activo'),
('Carlos Ramírez', 'cramirez@pitagora.cl', 'admin123', 'admin', NULL, '+56966669999', 'Activo'),
('Pedro Soto', 'psoto@pitagora.cl', 'obra2026', 'jefe_obra', 3, '+56955551111', 'Activo'),
('Ana Martínez', 'amartinez@pitagora.cl', 'obra2026', 'jefe_obra', 4, '+56944442222', 'Activo'),
('Luis Fernández', 'lfernandez@pitagora.cl', 'obra2026', 'jefe_obra', 5, '+56933333333', 'Activo'),
('Jorge Electricista', 'jelectricista@pitagora.cl', 'tec2026', 'tecnico', NULL, '+56922224444', 'Activo'),
('Carmen Gasfiter', 'cgasfiter@pitagora.cl', 'tec2026', 'tecnico', NULL, '+56911115555', 'Activo'),
('Diego Pintor', 'dpintor@pitagora.cl', 'tec2026', 'tecnico', NULL, '+56900006666', 'Activo'),
('Patricia Carpintera', 'pcarpintera@pitagora.cl', 'tec2026', 'tecnico', NULL, '+56988887777', 'Activo'),
('Cliente Vista Hermosa', 'cliente@vistahermosa.cl', 'cli2026', 'cliente', 3, '+56977771111', 'Activo'),
('Cliente Del Sur', 'cliente@delsur.cl', 'cli2026', 'cliente', 4, '+56966662222', 'Activo'),
('Cliente Pacifico', 'cliente@pacifico.cl', 'cli2026', 'cliente', 5, '+56955553333', 'Activo'),
('Cliente Urbanos', 'cliente@desarrollosurbanos.cl', 'cli2026', 'cliente', 6, '+56944444444', 'Activo'),
('Cliente Costa Verde', 'cliente@costaverde.cl', 'cli2026', 'cliente', 7, '+56933335555', 'Activo'),
('Cliente Robles', 'cliente@losrobles.cl', 'cli2026', 'cliente', 6, '+56922226666', 'Activo');

INSERT INTO `tickets` (`id_obra`, `id_usuario_creador`, `fecha_creacion`, `estado_general`) VALUES
(1, 4, '2026-05-05 10:30:00', 'abierto'),
(1, 4, '2026-05-06 14:20:00', 'en proceso'),
(1, 4, '2026-05-07 09:15:00', 'terminado'),
(3, 14, '2026-05-03 11:00:00', 'abierto'),
(3, 14, '2026-05-04 15:30:00', 'en proceso'),
(3, 14, '2026-05-05 08:45:00', 'en proceso'),
(3, 14, '2026-05-06 16:20:00', 'abierto'),
(3, 14, '2026-05-07 10:10:00', 'terminado'),
(4, 15, '2026-05-02 09:00:00', 'abierto'),
(4, 15, '2026-05-03 13:30:00', 'en proceso'),
(4, 15, '2026-05-04 11:15:00', 'en proceso'),
(4, 15, '2026-05-05 14:45:00', 'abierto'),
(4, 15, '2026-05-06 10:30:00', 'terminado'),
(4, 15, '2026-05-07 15:00:00', 'abierto'),
(5, 16, '2026-05-01 10:00:00', 'abierto'),
(5, 16, '2026-05-02 14:30:00', 'en proceso'),
(5, 16, '2026-05-03 09:20:00', 'en proceso'),
(5, 16, '2026-05-04 16:10:00', 'terminado'),
(5, 16, '2026-05-05 11:40:00', 'abierto'),
(6, 17, '2026-05-03 08:30:00', 'abierto'),
(6, 17, '2026-05-04 12:00:00', 'en proceso'),
(6, 17, '2026-05-05 15:30:00', 'abierto'),
(2, 4, '2026-05-02 10:00:00', 'abierto'),
(2, 4, '2026-05-03 14:00:00', 'en proceso'),
(2, 4, '2026-05-04 09:30:00', 'terminado'),
(8, 18, '2026-05-01 11:00:00', 'abierto'),
(8, 18, '2026-05-02 15:00:00', 'en proceso'),
(9, 19, '2026-05-03 10:30:00', 'abierto'),
(9, 19, '2026-05-04 13:45:00', 'en proceso'),
(9, 19, '2026-05-05 16:20:00', 'terminado');

INSERT INTO `observaciones` (`id_ticket`, `id_categoria`, `falla`, `ubicacion_exacta`, `descripcion_problema`, `urgencia`, `estado_observacion`, `confirmacion_cliente`, `token_aceptacion`) VALUES
(2, 6, 'Puerta no cierra bien', 'Depto 301, puerta principal', 'La puerta principal no cierra correctamente, se queda trabada', 'media', 'pendiente', 'pendiente', 'token_001'),
(2, 9, 'Enchufes sin corriente', 'Depto 301, dormitorio 2', 'Dos enchufes del dormitorio 2 no tienen corriente', 'alta', 'en proceso', 'pendiente', 'token_002'),
(3, 3, 'Pintura con burbujas', 'Depto 305, living', 'Pintura del living presenta burbujas en varias zonas', 'baja', 'en observación', 'pendiente', 'token_003'),
(3, 10, 'Luminaria no enciende', 'Depto 305, cocina', 'La luminaria principal de la cocina no enciende', 'media', 'en proceso', 'pendiente', 'token_004'),
(4, 2, 'Filtración en baño', 'Depto 310, baño secundario', 'Filtración de agua en el techo del baño secundario', 'alta', 'terminado', 'aceptado', 'token_005'),
(4, 4, 'Cerámica trizada', 'Depto 310, cocina', 'Una cerámica del piso de la cocina está trizada', 'baja', 'terminado', 'aceptado', 'token_006'),
(5, 1, 'Llave gotea', 'Casa 5, baño principal', 'La llave del lavamanos gotea constantemente', 'media', 'pendiente', 'pendiente', 'token_007'),
(5, 7, 'Ventana no cierra', 'Casa 5, dormitorio principal', 'Ventana corredera no cierra completamente', 'alta', 'en observación', 'pendiente', 'token_008'),
(6, 3, 'Pintura rayada', 'Casa 8, pasillo', 'Pintura del pasillo tiene rayas y marcas', 'baja', 'en proceso', 'pendiente', 'token_009'),
(6, 8, 'Closet descuadrado', 'Casa 8, dormitorio 2', 'Puertas del closet están descuadradas', 'media', 'en proceso', 'pendiente', 'token_010'),
(7, 2, 'Filtración en techo', 'Casa 12, living', 'Mancha de humedad en el techo del living', 'alta', 'en proceso', 'pendiente', 'token_011'),
(7, 9, 'Enchufe quemado', 'Casa 12, cocina', 'Un enchufe de la cocina está quemado', 'alta', 'en proceso', 'pendiente', 'token_012'),
(8, 11, 'WC con fuga', 'Casa 15, baño principal', 'El WC pierde agua por la base', 'alta', 'pendiente', 'pendiente', 'token_013'),
(9, 4, 'Fragüe desprendido', 'Casa 18, baño secundario', 'El fragüe de las cerámicas se está desprendiendo', 'media', 'terminado', 'aceptado', 'token_014'),
(9, 10, 'Foco no enciende', 'Casa 18, terraza', 'El foco de la terraza no enciende', 'baja', 'terminado', 'aceptado', 'token_015'),
(10, 1, 'Ducha con baja presión', 'Depto 501, baño principal', 'La ducha tiene muy baja presión de agua', 'media', 'pendiente', 'pendiente', 'token_016'),
(10, 14, 'Mampara con filtración', 'Depto 501, baño principal', 'La mampara de la ducha filtra agua', 'alta', 'en observación', 'pendiente', 'token_017'),
(11, 6, 'Puerta rayada', 'Depto 605, puerta principal', 'La puerta principal tiene rayas profundas', 'baja', 'en proceso', 'pendiente', 'token_018'),
(11, 3, 'Pintura con manchas', 'Depto 605, dormitorio principal', 'Manchas en la pintura del dormitorio principal', 'media', 'en proceso', 'pendiente', 'token_019'),
(12, 5, 'Tablero salta', 'Depto 708, tablero eléctrico', 'El automático del tablero salta constantemente', 'alta', 'en proceso', 'pendiente', 'token_020'),
(12, 9, 'Enchufes flojos', 'Depto 708, living', 'Varios enchufes del living están flojos', 'media', 'en proceso', 'pendiente', 'token_021'),
(13, 2, 'Filtración en muro', 'Depto 810, dormitorio 2', 'Filtración de agua en el muro exterior', 'alta', 'pendiente', 'pendiente', 'token_022'),
(14, 13, 'Piso flotante suena', 'Depto 905, pasillo', 'El piso flotante del pasillo suena al caminar', 'baja', 'terminado', 'aceptado', 'token_023'),
(14, 10, 'Luminaria parpadea', 'Depto 905, cocina', 'La luminaria de la cocina parpadea', 'media', 'terminado', 'aceptado', 'token_024'),
(15, 7, 'Ventana con filtración', 'Depto 1002, living', 'La ventana del living filtra agua cuando llueve', 'alta', 'pendiente', 'pendiente', 'token_025'),
(16, 1, 'Llave suelta', 'Depto 201, cocina', 'La llave de la cocina está suelta', 'media', 'pendiente', 'pendiente', 'token_026'),
(16, 4, 'Cerámica suelta', 'Depto 201, baño', 'Dos cerámicas del baño suenan huecas', 'baja', 'pendiente', 'pendiente', 'token_027'),
(17, 3, 'Pintura descascarada', 'Depto 305, balcón', 'La pintura del balcón está descascarada', 'baja', 'en proceso', 'pendiente', 'token_028'),
(17, 12, 'Desagüe tapado', 'Depto 305, baño principal', 'El desagüe del baño está tapado', 'alta', 'en proceso', 'pendiente', 'token_029'),
(18, 6, 'Puerta no abre bien', 'Depto 408, dormitorio principal', 'La puerta del dormitorio principal no abre bien', 'media', 'en proceso', 'pendiente', 'token_030'),
(18, 9, 'Enchufe sin tapa', 'Depto 408, living', 'Un enchufe del living no tiene tapa', 'baja', 'en proceso', 'pendiente', 'token_031'),
(19, 2, 'Filtración bajo lavaplatos', 'Depto 510, cocina', 'Filtración de agua bajo el lavaplatos', 'alta', 'terminado', 'aceptado', 'token_032'),
(20, 8, 'Closet con puerta caída', 'Depto 605, dormitorio 2', 'Una puerta del closet está caída', 'media', 'pendiente', 'pendiente', 'token_033'),
(20, 10, 'Interruptor no funciona', 'Depto 605, pasillo', 'El interruptor del pasillo no funciona', 'media', 'pendiente', 'pendiente', 'token_034'),
(21, 1, 'Ducha gotea', 'Depto 102, baño principal', 'La ducha gotea después de cerrarla', 'media', 'pendiente', 'pendiente', 'token_035'),
(21, 7, 'Ventana rota', 'Depto 102, dormitorio 2', 'El vidrio de la ventana está quebrado', 'alta', 'en observación', 'pendiente', 'token_036'),
(22, 3, 'Pintura con burbujas', 'Depto 205, baño secundario', 'La pintura del baño tiene burbujas', 'baja', 'en proceso', 'pendiente', 'token_037'),
(22, 4, 'Cerámica trizada', 'Depto 205, cocina', 'Una cerámica de la cocina está trizada', 'media', 'en proceso', 'pendiente', 'token_038'),
(23, 5, 'Automático salta', 'Depto 308, tablero', 'El automático del tablero salta frecuentemente', 'alta', 'pendiente', 'pendiente', 'token_039'),
(24, 11, 'WC obstruido', 'Baño empleados, planta baja', 'El WC del baño de empleados está obstruido', 'alta', 'pendiente', 'pendiente', 'token_040'),
(24, 10, 'Luminarias no encienden', 'Bodega A, sector norte', 'Varias luminarias del sector norte no encienden', 'media', 'pendiente', 'pendiente', 'token_041'),
(25, 6, 'Portón con falla', 'Acceso principal', 'El portón automático no abre correctamente', 'alta', 'en proceso', 'pendiente', 'token_042'),
(25, 9, 'Enchufes industriales flojos', 'Bodega B, sector sur', 'Los enchufes industriales están flojos', 'media', 'en proceso', 'pendiente', 'token_043'),
(26, 2, 'Filtración en techo', 'Bodega C, sector este', 'Filtración de agua en el techo de la bodega', 'alta', 'terminado', 'aceptado', 'token_044'),
(27, 1, 'Llave de paso con fuga', 'Bodega 1, baño', 'La llave de paso del baño tiene fuga', 'alta', 'pendiente', 'pendiente', 'token_045'),
(27, 3, 'Pintura exterior deteriorada', 'Fachada norte', 'La pintura de la fachada norte está deteriorada', 'baja', 'pendiente', 'pendiente', 'token_046'),
(28, 5, 'Tablero eléctrico con problemas', 'Bodega 3, tablero principal', 'El tablero eléctrico presenta problemas', 'alta', 'en proceso', 'pendiente', 'token_047'),
(29, 7, 'Ventana con condensación', 'Depto 101, living', 'Las ventanas del living tienen condensación', 'media', 'pendiente', 'pendiente', 'token_048'),
(29, 13, 'Piso con desnivel', 'Depto 101, pasillo', 'El piso del pasillo tiene un desnivel', 'baja', 'pendiente', 'pendiente', 'token_049'),
(30, 2, 'Filtración en balcón', 'Depto 205, balcón', 'Filtración de agua en el balcón', 'alta', 'en proceso', 'pendiente', 'token_050'),
(30, 4, 'Fragüe con hongos', 'Depto 205, baño principal', 'El fragüe del baño tiene hongos', 'media', 'en proceso', 'pendiente', 'token_051'),
(31, 8, 'Closet con humedad', 'Depto 308, dormitorio principal', 'El closet presenta humedad en el fondo', 'alta', 'terminado', 'aceptado', 'token_052'),
(31, 10, 'Foco LED quemado', 'Depto 308, cocina', 'El foco LED de la cocina está quemado', 'baja', 'terminado', 'aceptado', 'token_053');

INSERT INTO `evidencias` (`id_observacion`, `url_archivo`, `tipo_archivo`, `momento`) VALUES
(3, 'https://storage.pitagora.cl/evidencia/obs_003_antes.jpg', 'imagen', 'antes'),
(4, 'https://storage.pitagora.cl/evidencia/obs_004_antes.jpg', 'imagen', 'antes'),
(5, 'https://storage.pitagora.cl/evidencia/obs_005_antes.jpg', 'imagen', 'antes'),
(5, 'https://storage.pitagora.cl/evidencia/obs_005_despues.jpg', 'imagen', 'despues'),
(6, 'https://storage.pitagora.cl/evidencia/obs_006_antes.jpg', 'imagen', 'antes'),
(6, 'https://storage.pitagora.cl/evidencia/obs_006_despues.jpg', 'imagen', 'despues'),
(7, 'https://storage.pitagora.cl/evidencia/obs_007_antes.jpg', 'imagen', 'antes'),
(8, 'https://storage.pitagora.cl/evidencia/obs_008_antes.jpg', 'imagen', 'antes'),
(11, 'https://storage.pitagora.cl/evidencia/obs_011_antes.jpg', 'imagen', 'antes'),
(12, 'https://storage.pitagora.cl/evidencia/obs_012_antes.jpg', 'imagen', 'antes'),
(13, 'https://storage.pitagora.cl/evidencia/obs_013_antes.jpg', 'imagen', 'antes'),
(17, 'https://storage.pitagora.cl/evidencia/obs_017_antes.jpg', 'imagen', 'antes'),
(20, 'https://storage.pitagora.cl/evidencia/obs_020_antes.jpg', 'imagen', 'antes'),
(22, 'https://storage.pitagora.cl/evidencia/obs_022_antes.jpg', 'imagen', 'antes'),
(25, 'https://storage.pitagora.cl/evidencia/obs_025_antes.jpg', 'imagen', 'antes'),
(29, 'https://storage.pitagora.cl/evidencia/obs_029_antes.jpg', 'imagen', 'antes'),
(32, 'https://storage.pitagora.cl/evidencia/obs_032_antes.jpg', 'imagen', 'antes'),
(32, 'https://storage.pitagora.cl/evidencia/obs_032_despues.jpg', 'imagen', 'despues'),
(36, 'https://storage.pitagora.cl/evidencia/obs_036_antes.jpg', 'imagen', 'antes'),
(39, 'https://storage.pitagora.cl/evidencia/obs_039_antes.jpg', 'imagen', 'antes'),
(42, 'https://storage.pitagora.cl/evidencia/obs_042_antes.jpg', 'imagen', 'antes'),
(44, 'https://storage.pitagora.cl/evidencia/obs_044_antes.jpg', 'imagen', 'antes'),
(44, 'https://storage.pitagora.cl/evidencia/obs_044_despues.jpg', 'imagen', 'despues'),
(47, 'https://storage.pitagora.cl/evidencia/obs_047_antes.jpg', 'imagen', 'antes'),
(50, 'https://storage.pitagora.cl/evidencia/obs_050_antes.jpg', 'imagen', 'antes'),
(52, 'https://storage.pitagora.cl/evidencia/obs_052_antes.jpg', 'imagen', 'antes'),
(52, 'https://storage.pitagora.cl/evidencia/obs_052_despues.jpg', 'imagen', 'despues');

INSERT INTO `mensajes` (`id_observacion`, `id_usuario`, `mensaje`) VALUES
(3, 1, 'Se agendó visita técnica para evaluar el problema de pintura.'),
(4, 10, 'Revisé la luminaria, necesita cambio de balasto.'),
(7, 11, 'La llave necesita cambio de empaquetadura.'),
(8, 2, 'Coordinando con proveedor de ventanas para reparación.'),
(11, 11, 'Se detectó filtración desde el piso superior, coordinando con vecino.'),
(12, 10, 'El enchufe está quemado, se requiere cambio completo.'),
(17, 1, 'Se solicitó cotización para reparación de mampara.'),
(20, 10, 'El tablero tiene sobrecarga, se requiere redistribución de circuitos.'),
(22, 11, 'La filtración viene del techo, se requiere impermeabilización.'),
(25, 2, 'Se agendó reparación de ventana para el próximo lunes.'),
(29, 11, 'El desagüe requiere limpieza profunda con máquina.'),
(32, 1, 'Filtración reparada exitosamente, se aplicó sellante.'),
(36, 1, 'Se coordinó cambio de vidrio con proveedor.'),
(39, 10, 'Se requiere revisión del tablero general del edificio.'),
(42, 2, 'El portón necesita ajuste del motor automático.'),
(47, 10, 'Se detectó problema en el tablero principal, requiere electricista especializado.'),
(50, 11, 'Se aplicó impermeabilizante en el balcón.'),
(52, 12, 'Se eliminó la humedad y se aplicó antihongos.');

INSERT INTO `historial_bitacora` (`id_observacion`, `id_usuario`, `accion`, `detalles`) VALUES
(3, 4, 'Creación de observación', 'Cliente reporta problema de pintura con burbujas'),
(3, 1, 'Cambio de estado a En Observación', 'Se agenda visita técnica'),
(4, 4, 'Creación de observación', 'Cliente reporta luminaria que no enciende'),
(4, 1, 'Cambio de estado a En Proceso', 'Se asigna técnico electricista'),
(5, 4, 'Creación de observación', 'Cliente reporta filtración en baño'),
(5, 1, 'Cambio de estado a En Proceso', 'Se asigna técnico gasfiter'),
(5, 1, 'Cambio de estado a Terminado', 'Reparación completada exitosamente'),
(6, 4, 'Creación de observación', 'Cliente reporta cerámica trizada'),
(6, 1, 'Cambio de estado a Terminado', 'Se reemplazó la cerámica'),
(7, 14, 'Creación de observación', 'Cliente reporta llave que gotea'),
(8, 14, 'Creación de observación', 'Cliente reporta ventana que no cierra'),
(8, 1, 'Cambio de estado a En Observación', 'Se agenda revisión técnica'),
(11, 14, 'Creación de observación', 'Cliente reporta filtración en techo'),
(11, 1, 'Cambio de estado a En Proceso', 'Se coordina con vecino del piso superior'),
(12, 14, 'Creación de observación', 'Cliente reporta enchufe quemado'),
(12, 1, 'Cambio de estado a En Proceso', 'Se asigna técnico electricista'),
(17, 15, 'Creación de observación', 'Cliente reporta mampara con filtración'),
(17, 1, 'Cambio de estado a En Observación', 'Se solicita cotización'),
(20, 15, 'Creación de observación', 'Cliente reporta tablero que salta'),
(20, 1, 'Cambio de estado a En Proceso', 'Se asigna electricista especializado'),
(22, 15, 'Creación de observación', 'Cliente reporta filtración en muro'),
(25, 15, 'Creación de observación', 'Cliente reporta ventana con filtración'),
(29, 16, 'Creación de observación', 'Cliente reporta desagüe tapado'),
(29, 1, 'Cambio de estado a En Proceso', 'Se agenda limpieza con máquina'),
(32, 16, 'Creación de observación', 'Cliente reporta filtración bajo lavaplatos'),
(32, 1, 'Cambio de estado a En Proceso', 'Se asigna técnico gasfiter'),
(32, 1, 'Cambio de estado a Terminado', 'Filtración reparada con sellante'),
(36, 17, 'Creación de observación', 'Cliente reporta ventana rota'),
(36, 1, 'Cambio de estado a En Observación', 'Se coordina cambio de vidrio'),
(39, 17, 'Creación de observación', 'Cliente reporta automático que salta'),
(42, 4, 'Creación de observación', 'Cliente reporta portón con falla'),
(42, 1, 'Cambio de estado a En Proceso', 'Se asigna técnico especializado'),
(44, 4, 'Creación de observación', 'Cliente reporta filtración en techo'),
(44, 1, 'Cambio de estado a En Proceso', 'Se aplica impermeabilizante'),
(44, 1, 'Cambio de estado a Terminado', 'Impermeabilización completada'),
(47, 18, 'Creación de observación', 'Cliente reporta tablero eléctrico con problemas'),
(47, 1, 'Cambio de estado a En Proceso', 'Se asigna electricista especializado'),
(50, 19, 'Creación de observación', 'Cliente reporta filtración en balcón'),
(50, 1, 'Cambio de estado a En Proceso', 'Se aplica impermeabilizante'),
(52, 19, 'Creación de observación', 'Cliente reporta closet con humedad'),
(52, 1, 'Cambio de estado a En Proceso', 'Se aplica tratamiento antihongos'),
(52, 1, 'Cambio de estado a Terminado', 'Tratamiento completado exitosamente');

SELECT 'Script ejecutado exitosamente!' AS Resultado;
SELECT 'Datos poblados en la base de datos postventa_test' AS Info;
SELECT COUNT(*) AS 'Total Tickets' FROM tickets;
SELECT COUNT(*) AS 'Total Observaciones' FROM observaciones;
SELECT COUNT(*) AS 'Total Usuarios' FROM usuarios;
SELECT COUNT(*) AS 'Total Obras' FROM obras;


